---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: network-attachment-definitions.k8s.cni.cncf.io
spec:
  group: k8s.cni.cncf.io
  version: v1
  scope: Namespaced
  names:
    plural: network-attachment-definitions
    singular: network-attachment-definition
    kind: NetworkAttachmentDefinition
    shortNames:
    - net
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            config:
                 type: string
---
apiVersion: "k8s.cni.cncf.io/v1"
# apiVersion: "kubernetes.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: external
  namespace: ftp
spec: 
  config: '{
            "cniVersion": "0.3.0",
            "type": "macvlan",
            "master": "ens224",
            "isDefaultGateway":true,
            "mode": "bridge",
            "ipam": {
                "type": "host-local",
                "subnet": "10.34.10.0/24",
                "rangeStart": "10.34.10.150",
                "rangeEnd": "10.34.10.250",
                "routes": [
                    { "dst": "0.0.0.0/0" }
                ],
                "gateway": "10.34.10.1"
            }
        }'
# ---
# apiVersion: "kubernetes.com/v1"
# # apiVersion: "kubernetes.cni.cncf.io/v1"
# kind: Network
# metadata:
#   name: ens224
# spec: 
#   config: '{
#             "cniVersion": "0.3.0",
#             "type": "macvlan",
#             "master": "ens224",
#             "name": "macvlan.1",
#             "mode": "bridge",
#             "ipam": {
#                 "type": "dhcp",
#                 "subnet": "10.34.10.0/24",
#                 "rangeStart": "10.34.10.150",
#                 "rangeEnd": "10.34.10.250",
#                 "routes": [
#                     { "dst": "0.0.0.0/0" }
#                 ],
#                 "gateway": "10.34.10.1"
#             }
#         }'