apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
 name: flannel-networkobj
plugin: flannel
args: '[
 {
 "delegate": {
 "isDefaultGateway": true
 }
 }
]'

---
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
 name: flannel-conf
plugin: flannel
args: '[
 {
 "delegate": {
 "isDefaultGateway": true
 }
 }
]'
--
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
 name: sriov-conf
plugin: sriov
args: '[
       {
         "if0": "enp12s0f1",
         "ipam": {
         "type": "host-local",
         "subnet": "110.34.10.0/24",
         "rangeStart": "10.34.10.171",
         "rangeEnd": "10.34.10.181",
         "routes": [
           { "dst": "0.0.0.0/0" }
           ],
           "gateway": "10.34.10.1"
           }
       }
      ]'

apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
 name: sriov-vlanid-l2enable-conf
plugin: sriov
args: '[
 {
 "if0": "ens224",
 "vlan": 210,
 "if0name": "north",
 "l2enable": true
 }
]'